# Generated by Django 5.0.6 on 2024-05-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_identifier', models.CharField(max_length=50)),
                ('item_weight', models.FloatField(null=True)),
                ('item_fat_content', models.CharField(max_length=20)),
                ('item_visibility', models.FloatField()),
                ('item_type', models.CharField(max_length=50)),
                ('item_mrp', models.FloatField()),
                ('outlet_identifier', models.CharField(max_length=20)),
                ('outlet_establishment_year', models.IntegerField()),
                ('outlet_size', models.CharField(max_length=20, null=True)),
                ('outlet_location_type', models.CharField(max_length=20)),
                ('outlet_type', models.CharField(max_length=20)),
                ('item_outlet_sales', models.FloatField()),
            ],
        ),
    ]
